<script src="https://checkout.stripe.com/checkout.js"></script>
<div class="wo_about_wrapper_parent">
	<div class="wo_about_wrapper"> 
		<div class="hero hero-overlay"> 
			<div class="container wo_go_pro">
				<div class="col-md-8">
					<h1 class="head_pro"><?php echo $wo['config']['siteName'];?> <span class="pro-badge">PRO</span></h1>
					<h1 class="main_head_pro"><?php echo $wo['lang']['pro_feature_control_profile'];?></h1>
				</div>
				<div class="col-md-4 hidden-rocket">
					<img src="<?php echo $wo['config']['theme_url'];?>/img/go-pro/rocket.svg" alt="go-pro"/>
				</div>
			</div> 
		</div>
	</div>
</div>

<div class="page-margin wo_about_page_margin">
	<div class="list-group text-center wo_pro_features">
		<div class="col-md-12">
			<h2><?php echo $wo['lang']['why_choose_pro'];?></h2>
		</div>
		<div class="col-sm-6 col-md-3">
			<img src="<?php echo $wo['config']['theme_url'];?>/img/go-pro/superhero.svg" alt="superhero"/>
			<h3><?php echo $wo['lang']['featured_member'];?></h3>
		</div>
		<div class="col-sm-6 col-md-3">
			<img src="<?php echo $wo['config']['theme_url'];?>/img/go-pro/lastseen.svg" alt="lastseen"/>
			<h3><?php echo $wo['lang']['show_hide_lastseen'];?></h3>
		</div>
		<div class="col-sm-6 col-md-3">
			<img src="<?php echo $wo['config']['theme_url'];?>/img/go-pro/post.svg" alt="post"/>
			<h3><?php echo $wo['lang']['post_promotion_star'];?></h3>
		</div>
		<div class="col-sm-6 col-md-3">
			<img src="<?php echo $wo['config']['theme_url'];?>/img/go-pro/verify.svg" alt="verify"/>
			<h3><?php echo $wo['lang']['verified_badge'];?></h3>
		</div>
	</div>

	<div class="pricing_table">
		<section>
			<div class="row">
				<?php if ($wo['pro_packages']['star']['status'] == 1) { ?>
				<div class="col-xs-12 col-sm-6 col-md-3">
					<ul class="pricing p-green">
						<li class="price-table-head">
							<?php if (!empty($wo['pro_packages']['star']['image'])) { ?>
								<div>
									<img src="<?php echo($wo['pro_packages']['star']['image']) ?>" class="pro_packages_icon">
								</div>
								<div class="clearfix"></div>
							<?php }else{ ?>
								<big><i class="fa fa-star"></i></big>
							<?php } ?>
							<h3><?php echo Wo_GetCurrency($wo['config']['currency']);?><?php echo $wo['pro_packages']['star']['price'];?></h3>
							<span><?php 
							if ($wo['pro_packages']['star']['time'] == 7) {
								echo $wo['lang']['per_week'];
							}
							elseif ($wo['pro_packages']['star']['time'] == 30) {
								echo $wo['lang']['per_month'];
							}
							elseif ($wo['pro_packages']['star']['time'] == 365) {
								echo $wo['lang']['per_year'];
							}
							elseif ($wo['pro_packages']['star']['time'] == 0) {
								echo $wo['lang']['life_time'];
							}
							else{
								echo $wo['pro_packages']['star']['time'].' '.$wo['lang']['day'];
							}
							?></span>
						</li>
						<li class="plan-name"><big><?php echo $wo['lang']['star'];?></big></li>
						<li>
							<?php if ($wo['pro_packages']['star']['featured_member']) { ?>
								<i class="fa fa-check green"></i>
							<?php }else{ ?>
								<i class="fa fa-times red"></i>
							<?php } ?>
							 <?php echo $wo['lang']['featured_member'];?>
						</li>
						<li>
							<?php if ($wo['pro_packages']['star']['profile_visitors']) { ?>
								<i class="fa fa-check green"></i>
							<?php }else{ ?>
								<i class="fa fa-times red"></i>
							<?php } ?>
							<?php echo $wo['lang']['see_profile_visitors'];?>
						</li>
						<li>
							<?php if ($wo['pro_packages']['star']['last_seen']) { ?>
								<i class="fa fa-check green"></i>
							<?php }else{ ?>
								<i class="fa fa-times red"></i>
							<?php } ?> 
							<?php echo $wo['lang']['show_hide_lastseen'];?>
						</li>
						<li>
							<?php if ($wo['pro_packages']['star']['verified_badge']) { ?>
								<i class="fa fa-check green"></i>
							<?php }else{ ?>
								<i class="fa fa-times red"></i>
							<?php } ?>
							<?php echo $wo['lang']['verified_badge'];?>
						</li>
						<li>
							<?php if (!empty($wo['pro_packages']['star']['posts_promotion']) && is_numeric($wo['pro_packages']['star']['posts_promotion']) && $wo['pro_packages']['star']['posts_promotion'] > 0) { ?>
								<i class="fa fa-check green"></i>
								<?php 
								$post_promotion_star = str_replace('{monthly_boosts}', $wo['pro_packages']['star']['posts_promotion'], $wo['lang']['post_promotion_hot']);
								echo $post_promotion_star;
								?>
							<?php }else{ ?>
								<i class="fa fa-times red"></i><?php echo $wo['lang']['post_promotion_star'];?>
							<?php } ?>
						</li>
						<?php
						if ($wo['config']['pages'] == 1) {
						?>
							<li>
								<?php if (!empty($wo['pro_packages']['star']['pages_promotion']) && is_numeric($wo['pro_packages']['star']['pages_promotion']) && $wo['pro_packages']['star']['pages_promotion'] > 0) { ?>
									<i class="fa fa-check green"></i>
									<?php 
									$page_promotion_star = str_replace('{monthly_boosts}', $wo['pro_packages']['star']['pages_promotion'], $wo['lang']['post_promotion_hot']);
									echo $page_promotion_star;
									?>
								<?php }else{ ?>
									<i class="fa fa-times red"></i><?php echo $wo['lang']['page_promotion_star'];?>
								<?php } ?>
							</li>
						<?php } ?>
						<li>
							<?php if (!empty($wo['pro_packages']['star']['discount']) && is_numeric($wo['pro_packages']['star']['discount']) && $wo['pro_packages']['star']['discount'] > 0) { ?>
								<?php echo $wo['pro_packages']['star']['discount']."% ".$wo['lang']['discount']; ?>
							<?php }else{ ?>
								<i class="fa fa-times red"></i> <?php echo $wo['lang']['discount'];?>
							<?php } ?>
						</li>
						<li>
							<button class="button-week" onclick="Wo_GetPaymentLink(1);"><?php echo $wo['lang']['upgrade_now'];?></button>
						</li>
					</ul>
				</div>
				<?php } ?>
				<?php if ($wo['pro_packages']['hot']['status'] == 1) { ?>
				<div class="col-xs-12 col-sm-6 col-md-3">
					<ul class="pricing p-yel">
						<li class="price-table-head">
							<?php if (!empty($wo['pro_packages']['hot']['image'])) { ?>
								<div>
									<img src="<?php echo($wo['pro_packages']['hot']['image']) ?>" class="pro_packages_icon">
								</div>
								<div class="clearfix"></div>
							<?php }else{ ?>
								<big><i class="fa fa-fire"></i></big>
							<?php } ?>
							<h3><?php echo Wo_GetCurrency($wo['config']['currency']);?><?php echo $wo['pro_packages']['hot']['price'];?></h3>
							<span><?php 
							if ($wo['pro_packages']['hot']['time'] == 7) {
								echo $wo['lang']['per_week'];
							}
							elseif ($wo['pro_packages']['hot']['time'] == 30) {
								echo $wo['lang']['per_month'];
							}
							elseif ($wo['pro_packages']['hot']['time'] == 365) {
								echo $wo['lang']['per_year'];
							}
							elseif ($wo['pro_packages']['hot']['time'] == 0) {
								echo $wo['lang']['life_time'];
							}
							else{
								echo $wo['pro_packages']['hot']['time'].' '.$wo['lang']['day'];
							}

							?></span>
						</li>
						<li class="plan-name"><big><?php echo $wo['lang']['hot'];?></big></li>
						<li>
							<?php if ($wo['pro_packages']['hot']['featured_member']) { ?>
								<i class="fa fa-check green"></i>
							<?php }else{ ?>
								<i class="fa fa-times red"></i>
							<?php } ?>
							<?php echo $wo['lang']['featured_member'];?>
						</li>
						<li>
							<?php if ($wo['pro_packages']['hot']['profile_visitors']) { ?>
								<i class="fa fa-check green"></i>
							<?php }else{ ?>
								<i class="fa fa-times red"></i>
							<?php } ?>
							<?php echo $wo['lang']['see_profile_visitors'];?>
						</li>
						<li>
							<?php if ($wo['pro_packages']['hot']['last_seen']) { ?>
								<i class="fa fa-check green"></i>
							<?php }else{ ?>
								<i class="fa fa-times red"></i>
							<?php } ?> 
							<?php echo $wo['lang']['show_hide_lastseen'];?>
						</li>
						<li>
							<?php if ($wo['pro_packages']['hot']['verified_badge']) { ?>
								<i class="fa fa-check green"></i>
							<?php }else{ ?>
								<i class="fa fa-times red"></i>
							<?php } ?>
							<?php echo $wo['lang']['verified_badge'];?>
						</li>
						<li>
							<?php if (!empty($wo['pro_packages']['hot']['posts_promotion']) && is_numeric($wo['pro_packages']['hot']['posts_promotion']) && $wo['pro_packages']['hot']['posts_promotion'] > 0) { ?>
								<i class="fa fa-check green"></i>
								<?php 
								$post_promotion_hot = str_replace('{monthly_boosts}', $wo['pro_packages']['hot']['posts_promotion'], $wo['lang']['page_promotion_hot']);
								echo $post_promotion_hot;
								?>
							<?php }else{ ?>
								<i class="fa fa-times red"></i><?php echo $wo['lang']['post_promotion_star'];?>
							<?php } ?>
						</li>
						<?php
						if ($wo['config']['pages'] == 1) {
						?>
							<li>
								<?php if (!empty($wo['pro_packages']['hot']['pages_promotion']) && is_numeric($wo['pro_packages']['hot']['pages_promotion']) && $wo['pro_packages']['hot']['pages_promotion'] > 0) { ?>
									<i class="fa fa-check green"></i>
									<?php 
									$page_promotion_hot = str_replace('{monthly_boosts}', $wo['pro_packages']['hot']['pages_promotion'], $wo['lang']['page_promotion_hot']);
									echo $page_promotion_hot;
									?>
								<?php }else{ ?>
									<i class="fa fa-times red"></i><?php echo $wo['lang']['page_promotion_star'];?>
								<?php } ?>
							</li>
						<?php } ?>
						<li>
							<?php if (!empty($wo['pro_packages']['hot']['discount']) && is_numeric($wo['pro_packages']['hot']['discount']) && $wo['pro_packages']['hot']['discount'] > 0) { ?>
								<?php echo $wo['pro_packages']['hot']['discount']."% ".$wo['lang']['discount']; ?>
							<?php }else{ ?>
								<i class="fa fa-times red"></i> <?php echo $wo['lang']['discount'];?>
							<?php } ?>
						</li>
						<li>
							<button class="button-month" onclick="Wo_GetPaymentLink(2);"><?php echo $wo['lang']['upgrade_now'];?></button>
						</li>
					</ul>
				</div>
				<?php } ?>
				<?php if ($wo['pro_packages']['ultima']['status'] == 1) { ?>
				<div class="col-xs-12 col-sm-6 col-md-3 ">
					<ul class="pricing p-red">
						<li class="price-table-head">
							<?php if (!empty($wo['pro_packages']['ultima']['image'])) { ?>
								<div>
									<img src="<?php echo($wo['pro_packages']['ultima']['image']) ?>" class="pro_packages_icon">
								</div>
								<div class="clearfix"></div>
							<?php }else{ ?>
								<big><i class="fa fa-bolt"></i></big>
							<?php } ?>
							<h3><?php echo Wo_GetCurrency($wo['config']['currency']);?><?php echo $wo['pro_packages']['ultima']['price'];?></h3>
							<span><?php 
							if ($wo['pro_packages']['ultima']['time'] == 7) {
								echo $wo['lang']['per_week'];
							}
							elseif ($wo['pro_packages']['ultima']['time'] == 30) {
								echo $wo['lang']['per_month'];
							}
							elseif ($wo['pro_packages']['ultima']['time'] == 365) {
								echo $wo['lang']['per_year'];
							}
							elseif ($wo['pro_packages']['ultima']['time'] == 0) {
								echo $wo['lang']['life_time'];
							}
							else{
								echo $wo['pro_packages']['ultima']['time'].' '.$wo['lang']['day'];
							}
							?></span>
						</li>
						<li class="plan-name"><big><?php echo $wo['lang']['ultima'];?></big></li>
						<li>
							<?php if ($wo['pro_packages']['ultima']['featured_member']) { ?>
								<i class="fa fa-check green"></i>
							<?php }else{ ?>
								<i class="fa fa-times red"></i>
							<?php } ?>
							<?php echo $wo['lang']['featured_member'];?>
						 </li>
						<li>
							<?php if ($wo['pro_packages']['ultima']['profile_visitors']) { ?>
								<i class="fa fa-check green"></i>
							<?php }else{ ?>
								<i class="fa fa-times red"></i>
							<?php } ?>
							<?php echo $wo['lang']['see_profile_visitors'];?>
						</li>
						<li>
							<?php if ($wo['pro_packages']['ultima']['last_seen']) { ?>
								<i class="fa fa-check green"></i>
							<?php }else{ ?>
								<i class="fa fa-times red"></i>
							<?php } ?> 
							<?php echo $wo['lang']['show_hide_lastseen'];?>
						</li>
						<li>
							<?php if ($wo['pro_packages']['ultima']['verified_badge']) { ?>
								<i class="fa fa-check green"></i>
							<?php }else{ ?>
								<i class="fa fa-times red"></i>
							<?php } ?>
							<?php echo $wo['lang']['verified_badge'];?>
						</li>
						<li>
							<?php if (!empty($wo['pro_packages']['ultima']['posts_promotion']) && is_numeric($wo['pro_packages']['ultima']['posts_promotion']) && $wo['pro_packages']['ultima']['posts_promotion'] > 0) { ?>
								<i class="fa fa-check green"></i>
								<?php 
								$post_promotion_ultima = str_replace('{yearly_boosts}', $wo['pro_packages']['ultima']['posts_promotion'], $wo['lang']['post_promotion_ultima']);
								echo $post_promotion_ultima;
								?>
							<?php }else{ ?>
								<i class="fa fa-times red"></i><?php echo $wo['lang']['post_promotion_star'];?>
							<?php } ?>
						</li>
						<?php
						if ($wo['config']['pages'] == 1) {
						?>
							<li>
								<?php if (!empty($wo['pro_packages']['ultima']['pages_promotion']) && is_numeric($wo['pro_packages']['ultima']['pages_promotion']) && $wo['pro_packages']['ultima']['pages_promotion'] > 0) { ?>
									<i class="fa fa-check green"></i>
									<?php 
									$page_promotion_ultima = str_replace('{monthly_boosts}', $wo['pro_packages']['ultima']['pages_promotion'], $wo['lang']['page_promotion_hot']);
									echo $page_promotion_ultima;
									?>
								<?php }else{ ?>
									<i class="fa fa-times red"></i><?php echo $wo['lang']['page_promotion_star'];?>
								<?php } ?>
							</li>
						<?php } ?>
						<li>
							<?php if (!empty($wo['pro_packages']['ultima']['discount']) && is_numeric($wo['pro_packages']['ultima']['discount']) && $wo['pro_packages']['ultima']['discount'] > 0) { ?>
								<?php echo $wo['pro_packages']['ultima']['discount']."% ".$wo['lang']['discount']; ?>
							<?php }else{ ?>
								<i class="fa fa-times red"></i> <?php echo $wo['lang']['discount'];?>
							<?php } ?>
						</li>
						<li>
							<button class="button-year" onclick="Wo_GetPaymentLink(3);"><?php echo $wo['lang']['upgrade_now'];?></button>
						</li>
					</ul>
				</div>
				<?php } ?>
				<?php if ($wo['pro_packages']['vip']['status'] == 1) { ?>
				<div class="col-xs-12 col-sm-6 col-md-3">
					<ul class="pricing p-blue">
						<li class="price-table-head">
							<?php if (!empty($wo['pro_packages']['vip']['image'])) { ?>
								<div>
									<img src="<?php echo($wo['pro_packages']['vip']['image']) ?>" class="pro_packages_icon">
								</div>
								<div class="clearfix"></div>
							<?php }else{ ?>
								<big><i class="fa fa-rocket"></i></big>
							<?php } ?>
							<h3><?php echo Wo_GetCurrency($wo['config']['currency']);?><?php echo $wo['pro_packages']['vip']['price'];?></h3>
							<span><?php 
							if ($wo['pro_packages']['vip']['time'] == 7) {
								echo $wo['lang']['per_week'];
							}
							elseif ($wo['pro_packages']['vip']['time'] == 30) {
								echo $wo['lang']['per_month'];
							}
							elseif ($wo['pro_packages']['vip']['time'] == 365) {
								echo $wo['lang']['per_year'];
							} 
							elseif ($wo['pro_packages']['vip']['time'] == 0) {
								echo $wo['lang']['life_time'];
							}
							else{
								echo $wo['pro_packages']['vip']['time'].' '.$wo['lang']['day'];
							}
							?></span>
						</li>
						<li class="plan-name"><big><?php echo $wo['lang']['vip'];?></big></li>
						<li>
							<?php if ($wo['pro_packages']['vip']['featured_member']) { ?>
								<i class="fa fa-check green"></i>
							<?php }else{ ?>
								<i class="fa fa-times red"></i>
							<?php } ?>
							<?php echo $wo['lang']['featured_member'];?>
						</li>
						<li>
							<?php if ($wo['pro_packages']['vip']['profile_visitors']) { ?>
								<i class="fa fa-check green"></i>
							<?php }else{ ?>
								<i class="fa fa-times red"></i>
							<?php } ?>
							<?php echo $wo['lang']['see_profile_visitors'];?>
						</li>
						<li>
							<?php if ($wo['pro_packages']['vip']['last_seen']) { ?>
								<i class="fa fa-check green"></i>
							<?php }else{ ?>
								<i class="fa fa-times red"></i>
							<?php } ?> 
							<?php echo $wo['lang']['show_hide_lastseen'];?>
						</li>
						<li>
							<?php if ($wo['pro_packages']['vip']['verified_badge']) { ?>
								<i class="fa fa-check green"></i>
							<?php }else{ ?>
								<i class="fa fa-times red"></i>
							<?php } ?>
							<?php echo $wo['lang']['verified_badge'];?>
						</li>
						<li>
							<?php if (!empty($wo['pro_packages']['vip']['posts_promotion']) && is_numeric($wo['pro_packages']['vip']['posts_promotion']) && $wo['pro_packages']['vip']['posts_promotion'] > 0) { ?>
								<i class="fa fa-check green"></i>
								<?php 
								$post_promotion_vip = str_replace('{lifetime_boosts}', $wo['pro_packages']['vip']['posts_promotion'], $wo['lang']['post_promotion_vip']);
								echo $post_promotion_vip;
								?>
							<?php }else{ ?>
								<i class="fa fa-times red"></i><?php echo $wo['lang']['post_promotion_star'];?>
							<?php } ?>
						</li>
						<?php
						if ($wo['config']['pages'] == 1) {
						?>
							<li>

								<?php if (!empty($wo['pro_packages']['vip']['pages_promotion']) && is_numeric($wo['pro_packages']['vip']['pages_promotion']) && $wo['pro_packages']['vip']['pages_promotion'] > 0) { ?>
									<i class="fa fa-check green"></i>
									<?php 
									$page_promotion_vip = str_replace('{monthly_boosts}', $wo['pro_packages']['vip']['pages_promotion'], $wo['lang']['page_promotion_hot']);
									echo $page_promotion_vip;
									?>
								<?php }else{ ?>
									<i class="fa fa-times red"></i><?php echo $wo['lang']['page_promotion_star'];?>
								<?php } ?>
							</li>
						<?php } ?>
						<li>
							<?php if (!empty($wo['pro_packages']['vip']['discount']) && is_numeric($wo['pro_packages']['vip']['discount']) && $wo['pro_packages']['vip']['discount'] > 0) { ?>
								<?php echo $wo['pro_packages']['vip']['discount']."% ".$wo['lang']['discount']; ?>
							<?php }else{ ?>
								<i class="fa fa-times red"></i> <?php echo $wo['lang']['discount'];?>
							<?php } ?>
						</li>
						<li>
							<button class="button-life-time" onclick="Wo_GetPaymentLink(4);"><?php echo $wo['lang']['upgrade_now'];?></button>
						</li>
					</ul>
				</div>
				<?php } ?>
			</div><!-- /row -->
		</section>
	</div>
</div>
<div id="pay-modal"></div>
<script>
function pay_using_wallet(type,description){
	var result = confirm("Are you want to buy "+ description + " using your wallet balance?");
	if (result) {
		
		$('.btn-walletpay').attr('disabled', true).text("<?php echo $wo["lang"]["please_wait"]?>");
		$.post(Wo_Ajax_Requests_File() + '?f=pay_using_wallet', {type:type}, function(data) {
			if (data.status == 200) {
				window.location.href = data.url;
			} else {
				$('.btn-walletpay').attr('disabled', false).html("Problem While pay using wallet");
			}
		});
	 
	}
}
function Wo_GetPayPalLink(type) {
   	 $('.btn-paypal').attr('disabled', true).text("<?php echo $wo["lang"]["please_wait"]?>");
     $.post(Wo_Ajax_Requests_File() + '?f=get_paypal_url', {type:type}, function(data) {
         if (data.status == 200) {
             window.location.href = data.url;
         } else {
         	$('.btn-paypal').attr('disabled', false).html("PayPal App not set yet.");
         }
     });
}
function Wo_CheckOutCard(type, description, amount, payment_type) {
	if (payment_type == 'bitcoin') {
		$('.btn-bitcoin').attr('disabled', true).text("<?php echo $wo["lang"]["please_wait"]?>");
	} else if (payment_type == 'credit_card') {
		$('.btn-cart').attr('disabled', true).text("<?php echo $wo["lang"]["please_wait"]?>");
	} else if (payment_type == 'alipay') {
		$('.btn-alipay').attr('disabled', true).text("<?php echo $wo["lang"]["please_wait"]?>");
	}
	var img = 'star';
	if (type == 1) {
		img = 'star';
	} else if (type == 2) {
		img = 'hot';
	} else if (type == 3) {
		img = 'ultima';
	} else if (type == 4) {
		img = 'vip';
	}
	if (payment_type != 'bank_payment') {
		var handler = StripeCheckout.configure({
	        key: "<?php echo $wo['config']['stripe_id'];?>",
	        locale: 'english',
	        image: '<?php echo $wo['config']['theme_url']?>/img/' + img + '.png',
	        token: function(token) {
	          $('.modal-body').html('<i class="fa fa-spin fa-spinner"></i> <?php echo $wo['lang']['c_payment'] ?>');
	          $('#pay-go-pro').modal({
	             show: true
	            });
	          $.post(Wo_Ajax_Requests_File() + '?f=stripe_payment&pro_type=' + type, {stripeToken:token.id, amount:amount}, function (data) {
	          	 if (data.status == 200) {
	          	 	window.location.href = data.location;
	          	 } else {
	          	 	$('.modal-body').html('<i class="fa fa-spin fa-spinner"></i> <?php echo $wo['lang']['payment_declined'] ?>');
	          	 }
	          });
	        }
	    });
	}
    if (payment_type == 'bitcoin') {
		$.get(Wo_Ajax_Requests_File() + '?f=paypro_with_bitcoin&amount=' + (amount/100) + '&desc=' + description + '&usertype=' + type  , function (data) {
			if (data.status == 200) {
				$(data.html).appendTo('body').submit();
			}
		});

    	// handler.open({
        //    name: "<?php echo $wo['config']['siteName']?>",
        //    description: description,
        //    amount: amount,
        //    currency: '<?php echo $wo['config']['currency']?>',
        //    bitcoin: true,
        //    opened: function () {
        //    	  $('#pay-go-pro').modal('hide');
        //    	  $('.btn-bitcoin').attr('disabled', false).html("<i class='fa fa-bitcoin'></i> <?php echo $wo['lang']['bitcoin'] ?>");
        //    }
        // });
    } else if (payment_type == 'credit_card') {
    	handler.open({
           name: "<?php echo $wo['config']['siteName']?>",
           description: description,
           amount: amount,
           currency: '<?php echo $wo['config']['currency']?>',
           opened: function () {
           	  $('#pay-go-pro').modal('hide');
           	  $('.btn-cart').attr('disabled', false).html("<i class='fa fa-credit-card'></i> <?php echo $wo['lang']['credit_card'] ?>");
           }
        });
    } else if (payment_type == 'alipay') {
    	handler.open({
           name: "<?php echo $wo['config']['siteName']?>",
           description: description,
           amount: amount,
           alipay: true,
           currency: '<?php echo $wo['config']['currency']?>',
           opened: function () {
           	  $('#pay-go-pro').modal('hide');
           	  $('.btn-alipay').attr('disabled', false).html("<i class='fa fa-credit-card'></i> Alipay");
           }
        });
    } else if (payment_type == 'bank_payment') {
    	$('#configreset').click();
    	$(".prv-img").html('<div class="thumbnail-rendderer"><div><h4 class="bold"><?php echo $wo['lang']['drop_img_here']; ?></h4><div class="error-text-renderer"></div><div><span><?php echo $wo['lang']['or']; ?></span><p><?php echo $wo['lang']['browse_to_upload']; ?></p></div></div> </div>');
		$("#blog-alert").html('');
    	$('#bank_transfer_des').val(description);
    	$('#bank_transfer_type').val(type);
    	$('#pay-go-pro').modal('hide');
    	$('#bank_transfer_modal').modal({
             show: true
            });
    	
   	  
	}
    $(window).on('popstate', function() {
       handler.close();
    });
}
$(document).on('click', '#select-img', function(event) {
	$("#thumbnail").click()
});
$(document).on('change', '#thumbnail', function(event) {
	let imgPath = $(this)[0].files[0].name;
    if (typeof(FileReader) != "undefined") {
        let reader = new FileReader();
        reader.onload = function(e) {
			$('#receipt_img_preview').attr('src', e.target.result);
        }
        reader.readAsDataURL(this.files[0]);
    }
	$('#bank_transfer_modal').addClass('up_rec_img_ready');
});

function Wo_GetPaymentLink(type) {
	$.get(Wo_Ajax_Requests_File() + '?f=get_payment_method&type=' + type, function (data) {
        if (data.status == 200) {
          	$('#pay-modal').html(data.html);
          	$('#pay-go-pro').modal({
             show: true
            });

        }
    });
}
jQuery(document).ready(function($) {
	$('#bank_transfer_form').ajaxForm({
	  url: Wo_Ajax_Requests_File() + '?f=bank_transfer',
	  beforeSend: function() {
	    $('#bank_transfer_form').find('.ball-pulse').fadeIn(100);
	  },
	  success: function(data) {
	    if (data['status'] == 200) {
	    	$("#blog-alert").html('<div class="alert alert-success">'+ data['message'] +'</div>');
	    	setTimeout(function () {
	    		window.location = "<?php echo $wo['config']['site_url'];?>";
	    		$(".prv-img").html('<div class="thumbnail-rendderer"><div><h4 class="bold"><?php echo $wo['lang']['drop_img_here']; ?></h4><div class="error-text-renderer"></div><div><span><?php echo $wo['lang']['or']; ?></span><p><?php echo $wo['lang']['browse_to_upload']; ?></p></div></div> </div>');
	    		$("#blog-alert").html('');
	    		$('#configreset').click();

	    	},3000)
	    } else if (data['message']) {
	      $("#blog-alert").html('<div class="alert alert-danger">' + data['message'] + '</div>');
	    } 
	    $('#bank_transfer_form').find('.ball-pulse').fadeOut(100);
	}});
});
</script>

<div class="modal fade" id="bank_transfer_modal" role="dialog" data-keyboard="false">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title"><?php echo $wo['lang']['bank_transfer'] ?></h4>
			</div>
			<form class="form form-horizontal" method="post" id="bank_transfer_form" action="#">
				<div class="modal-body dt_bank_trans_modal">
					<div id="blog-alert"></div>
					
					<?php echo $wo['config']['bank_description'];?>
					
					<?php if (!empty($wo['config']['bank_transfer_note'])) { ?>
						<div class="dt_user_profile hide_alert_info_bank_trans">
							<span class="valign-wrapper">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M13,13H11V7H13M13,17H11V15H13M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z"></path></svg> Note:
							</span>
							<ul class="dt_prof_vrfy">
								<li><?php echo $wo['config']['bank_transfer_note'];?></li>
							</ul>
						</div>
					<?php } ?>
					<p class="dt_bank_trans_upl_rec"><a href="javascript:void(0);" onclick="$('#bank_transfer_modal').addClass('up_rec_active'); return false"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M14,2H6A2,2 0 0,0 4,4V20A2,2 0 0,0 6,22H18A2,2 0 0,0 20,20V8L14,2M13.5,16V19H10.5V16H8L12,12L16,16H13.5M13,9V3.5L18.5,9H13Z"></path></svg> <?php echo $wo['lang']['upload'] ?></a></p>
					<div class="upload_bank_receipts">
						<div onclick="document.getElementById('thumbnail').click(); return false">
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M14,2H6A2,2 0 0,0 4,4V20A2,2 0 0,0 6,22H18A2,2 0 0,0 20,20V8L14,2M13.5,16V19H10.5V16H8L12,12L16,16H13.5M13,9V3.5L18.5,9H13Z"></path></svg>
							<p><?php echo $wo['lang']['browse_to_upload']; ?></p>
							<img id="receipt_img_preview" src="">
						</div>
					</div>
					<input type="file" class="hidden" id="thumbnail" name="thumbnail" accept="image/*">
					<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
					<input name="image" type="file" id="upload" class="hidden">
					<input name="type" type="hidden" id="bank_transfer_type" class="hidden">
					<input name="description" type="hidden" id="bank_transfer_des" class="hidden">
					<input type="reset" id="configreset" value="Reset" class="hidden">
				</div>
				<div class="modal-footer">
					<div class="ball-pulse"><div></div><div></div><div></div></div>
					<button type="submit" class="btn btn-main"><?php echo $wo['lang']['publish']; ?></button>
				</div>
			</form>
		</div>
	</div>
</div>